### ISSUE TITLE
Define "request is unsuccessful" for 8.3 Queue Mode Operation

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#33]
TS 8.3, Queue Mode Operation
"If a request is unsuccessful then it is returned to the queue."
may cause serious problems! There may be several reasons for a request to fail.

So define, in which unsuccessful cases the request should be returned to the queue (only ACK timeout?).
When the request should not be returned to the queue (e.g. failed with COAP 4.02 Bad Option), what should be done with the left requests in the queue? Process them may result in unexpected behavior. 

When the request should be returned to the queue, should it be returned at the head or at the tail of the queue? Returning at the head may block the communication. Returning at the tail reorders the messages, which may also result in unexpected behavior.

Or are there any (undocumented?) assumptions about the requests usable for queue mode?

**Comment by boaks** [comment]
"OMA-DM-LightweightM2M-2015-0031-CR_Queue_Mode.doc"

    If a request is unsuccessful  – i.e. Server gives up on receiving an acknowledgment or  reset -then
    the request it is returnsed to the queue which has been **previously emptied**.

What is ment by **previously emptied**? Does this include to remove "unprocessed" requests?
e.g.
- 5 requests to a client pending
- 1. request is successfull
- 2. request is unsuccessfull

Does the queue then only contain the 2. request (because the other requests are **previously emptied**) or does the queue contain all requests except of the 1.

**Comment by ThGarnier** [comment]
addressed in  OMA-TS-LightweightM2M-V1_0-20150910-D and fix improved in  OMA-TS-LightweightM2M-V1_0-20151211-D
=> to be closed

**Comment by boaks** [comment]
OMA-TS-LightweightM2M-V1_0-20151211-D, 69:
 
"If the LWM2M Server is not successful in sending a request – i.e. Server gives up on receiving an acknowledgment or reset -,"

"If a request is unsuccessful then the request returns to the queue that has been previously fetched, to the same position in the queue."

If "request" and "message" are used in the meaning of RFC7252, "request" should be replaced by "message". And then the TS should clearly specify, that any ACK or RST is handled as "SUCCESS" ignoring any possible "piggybacked" response code (which may indicate an error, which is to be ignored).

Not specifying a "max retransmission" (as Coap RFC7252) means also, that, if any component (even in the middle) has problems either transfer the message or the ACK/RST, the device will not longer be able to receive requests from the LWM2M server until, some undefined process takes place to correct the queue.

**Comment by boaks** [comment]
OMA-TS-LightweightM2M-V1_0-20160407-C

still doesn't comply the CoAP RFC 7252 terms!

**Comment by hannestschofenig** [comment]
We tried to clarify the meaning of a successful delivery of a message to a client in #104. Based on that we should adapt the wording in the technical specification accordingly.  It is not about successfully sending a request from the LWM2M server to the LWM2M client but rather about receiving a response to a request. If the server fails to receive a response then it places the request message back to the original position in the queue.

Receiving a response from the LWM2M client containing an error code is still considered a successfully received response. How to deal with such an error is outside the scope of the LWM2M specification and is subject to the application layer processing. A LWM2M server may offer capabilities to manage the content of the queue to react to such error conditions (for example by deleting further messages from the queue after an error has been received from the client).

**Comment by balsmn** [comment]
@hannestschofenig We cannot agree more. Yes, in case of an error response, the message SHOULD be considered as processed and SHOULD be removed from queue. Whether it should be requeued or all the remaining messages should be emptied is for the application layer to decide.

Is it already part of a CR ?

**Comment by boaks** [comment]
> It is not about successfully sending a request from the LWM2M server to the LWM2M client but rather about receiving a response to a request.

I don't get that point!

Why should the respone be considered to be more important the ACK according queue mode?

So my impression until that was:

- usually CoAP retries a message several times, but if the retries expires, it's "assumed" that this is caused by "a message specific problem" and not to block the communication, resending this message is stopped to give other messages a chance.
- knowing, that the communication partner my not be reachable, this assumption has to be changed and therefore queue mode was added.
- but for this reason, only the ACK/RST is relevant.

Yes, if piggybacked response is used, there is no difference and therefore mostly no need to differentiate. But, if a separate response is considered, I would disagree, that a ACK would not be sufficient.

So the main question for me seems now: 
Is the queue mode intended to 
- serialize requests
- or to ensure proper message transport to endpoints, which are temporary not reachable?

**Comment by hannestschofenig** [comment]
Here are my views. 

A LWM2M server has to deal with several limitations in queue mode, namely 
   * It does not necessarily know whether it will be able to deliver a message to the client, for example, because the client may be sleeping.
   * It cannot just forward all requests it gets from applications because of the CoAP congestion control constraints. 

In order to find out whether a message was successfully forwarded from the LWM2M server to the LWM2M client the LWM2M server has to rely on a response. This response tells the server that the message has been received and processed (regardless of what the result of the processing was).

If message delivery fails, for example, because the message got lost due to network connectivity issues or because the LMW2M client is sleeping then CoAP re-transmission behavior will kick in. The server will try to resend the message up to a certain number of attempts. Then, at some point, it has to give up. 

The LWM2M server has to tell the application that something has gone wrong if the message cannot be delivered. This API is outside the scope of the LWM2M specification. Whether other messages in the queue could potentially be delivered to the LWM2M client depends on a number of different factors and will in generally not be possible to answer. One possible approach with dealing with such a situation is to (a) notify the application about the failure to deliver the message, and to (b) remove the message from the queue and let the LWM2M server process other messages instead. I could imagine that the LWM2M server will raise another flag if other messages also cannot be delivery for a certain amount of time. Maybe the IoT device got disconnected from the network for an extended period of time.

**Comment by boaks** [comment]
Sorry again, I don't disagree with your explanation, I disagree with the term "response", which is, in my opinion a defined term in CoAP RFC7252. I would like to replace just that term with "ACK/RST", which are in my opinion the terms for the message transport layer in RFC7252.

**Comment by hannestschofenig** [comment]
Ok. Now I believe I got it. 

We need reliable message transmission and this can come in CoAP in two variations, either via a 
  * CON followed by an ACK, or 
  * CON followed by a RST.

**Comment by boaks** [comment]
YES!

**Comment by hannestschofenig** [comment]
Covered in https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/115

**Comment by boaks** [comment]
Agreed, OMA-DM-LightweightM2M-2016-0117-CR_queue_mode_clarification will solve it.

**Comment by ThGarnier** [comment]
According to the last CR117 included in the Oct16 TS,  issue can be closed

**Comment by boaks** [comment]
Fixed with OMA-TS-LightweightM2M-V1_0-20161007-D
